#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
# kinda catpuccin
PS1='[\[\033[1m\033[38;2;202;158;230m\]\t\[\033[00m\] \[\033[1m\033[38;2;140;170;238m\]\u@\h\[\033[00m\] \[\033[1m\033[38;2;229;200;144m\]\W\[\033[00m\]]$ '
